version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: todo-db
    ports:
      - '27017:27017'
    volumes:
      - todo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-server
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    environment:
      DATABASE_URI: 'mongodb://mongodb:27017/todo-db'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  todo-data:
